export interface Perfume {
  id: string;
  name: string;
  description: string;
  notes: string[];
  price: number;
  originalPrice: number;
  size: string;
  image: string;
  category: "body-splash" | "tube";
}

export const bodySplashes: Perfume[] = [
  {
    id: "qaed-al-fursan",
    name: "Qaed Al Fursan",
    description: "Una fragancia árabe majestuosa que evoca la nobleza y elegancia de los caballeros del desierto. Aroma sofisticado con toques amaderados y especiados.",
    notes: ["Ámbar", "Madera de Oud", "Almizcle", "Especias orientales"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/qaed-al-fursan.jpg",
    category: "body-splash",
  },
  {
    id: "fakhar-lattafa",
    name: "Fakhar Lattafa",
    description: "Elegancia pura en cada aplicación. Una composición lujosa con patrones dorados que representa la opulencia y el refinamiento árabe.",
    notes: ["Rosa de Damasco", "Oud", "Ámbar gris", "Vainilla"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/fakhar-lattafa.jpg",
    category: "body-splash",
  },
  {
    id: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    description: "Inspirado en el café árabe tradicional. Una fragancia cálida y reconfortante con notas tostadas y dulces que envuelven los sentidos.",
    notes: ["Café árabe", "Cardamomo", "Azafrán", "Vainilla tostada"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/khamrah-qahwa.jpg",
    category: "body-splash",
  },
  {
    id: "sakeena",
    name: "Sakeena",
    description: "Una explosión de sensualidad en rojo y dorado. Fragancia vibrante y apasionada que irradia confianza y magnetismo personal.",
    notes: ["Rosa roja", "Azafrán", "Ámbar", "Sándalo"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/sakeena.jpg",
    category: "body-splash",
  },
  {
    id: "club-de-nuit",
    name: "Club de Nuit Intense Man",
    description: "El favorito masculino por excelencia. Una fragancia intensa y seductora perfecta para la noche, con un aura de misterio irresistible.",
    notes: ["Limón", "Piña", "Abedul", "Almizcle negro"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/club-de-nuit.jpg",
    category: "body-splash",
  },
  {
    id: "hayaati-gold-elixir",
    name: "Hayaati Gold Elixir",
    description: "Un elixir dorado de lujo que combina notas orientales con toques florales. La esencia de la elegancia árabe en su máxima expresión.",
    notes: ["Oro líquido", "Rosa turca", "Ámbar", "Sándalo cremoso"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/hayaati-gold-elixir.jpg",
    category: "body-splash",
  },
  {
    id: "hayaati-florence",
    name: "Hayaati Florence",
    description: "Fragancia floral y delicada con un toque romántico. Perfecta para quienes buscan frescura con sofisticación femenina.",
    notes: ["Peonía", "Rosa blanca", "Almizcle suave", "Vainilla"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/hayaati-florence.jpg",
    category: "body-splash",
  },
  {
    id: "khamrah",
    name: "Khamrah",
    description: "La fragancia más deseada. Una mezcla embriagadora de especias dulces y maderas preciosas que deja una estela inolvidable.",
    notes: ["Canela", "Dátiles", "Tabaco dulce", "Vainilla de Madagascar"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/khamrah.jpg",
    category: "body-splash",
  },
 
  {
    id: "hayaati-black",
    name: "Hayaati Black",
    description: "La versión oscura e intensa de Hayaati. Para quienes prefieren fragancias profundas con carácter masculino.",
    notes: ["Cuero", "Oud negro", "Incienso", "Almizcle oscuro"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/hayaati-black.jpg",
    category: "body-splash",
  },
  {
    id: "khamrah-dukhan",
    name: "Khamrah Dukhan",
    description: "Variante ahumada de Khamrah con notas de incienso árabe. Una experiencia olfativa única y envolvente.",
    notes: ["Incienso", "Oud ahumado", "Azafrán", "Ámbar negro"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/khamrah-dukhan.jpg",
    category: "body-splash",
  },
  {
    id: "mayar",
    name: "Mayar",
    description: "Fragancia femenina delicada en tonos rosados. Fresca, floral y perfecta para el uso diario con un toque de distinción.",
    notes: ["Rosa de mayo", "Pera", "Almizcle blanco", "Sándalo"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/mayar.jpg",
    category: "body-splash",
  },
  {
    id: "lail-maliki",
    name: "Lail Maliki",
    description: "Noche real. Una fragancia nocturna con diseños orientales que evoca la magia de las noches árabes.",
    notes: ["Jazmín nocturno", "Oud real", "Almizcle", "Vainilla negra"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/lail-maliki.jpg",
    category: "body-splash",
  },
  {
    id: "ramz-lattafa",
    name: "Ramz Lattafa",
    description: "El símbolo de Lattafa. Fragancia unisex moderna con un diseño distintivo y notas versátiles para cualquier ocasión.",
    notes: ["Bergamota", "Lavanda", "Madera de gaiac", "Ámbar gris"],
    price: 25000,
    originalPrice: 30000,
    size: "250ml",
    image: "/products/ramz-lattafa.jpg",
    category: "body-splash",
  },
];

export const tubes: Perfume[] = [
  {
    id: "khamrah-tube",
    name: "Khamrah",
    description: "Perfume concentrado en formato travel. La esencia de la opulencia árabe en un práctico tubito de 35ml.",
    notes: ["Dátiles", "Canela", "Tabaco dulce", "Vainilla"],
    price: 4000,
    originalPrice: 5000,
    size: "35ml",
    image: "/products/khamrah-tube.jpg",
    category: "tube",
  },
  {
    id: "asad-tube",
    name: "Asad",
    description: "El león de las fragancias. Perfume intenso y poderoso con el sello distintivo del diseño árabe de lujo.",
    notes: ["Tabaco", "Café", "Ámbar", "Madera de cedro"],
    price: 4000,
    originalPrice: 5000,
    size: "35ml",
    image: "/products/asad-tube.jpg",
    category: "tube",
  },
];

export const allProducts = [...bodySplashes, ...tubes];
